2020-08-04 07:38:10,432 672 INFO ? odoo: Odoo version 13.0-20200803 
2020-08-04 07:38:10,432 672 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 13.0\server\odoo.conf 
2020-08-04 07:38:10,433 672 INFO ? odoo: addons paths: ['C:\\Program Files (x86)\\Odoo 13.0\\server\\odoo\\addons', 'c:\\users\\administrator\\appdata\\local\\openerp s.a\\odoo\\addons\\13.0', 'c:\\program files (x86)\\odoo 13.0\\server\\odoo\\addons'] 
2020-08-04 07:38:10,433 672 INFO ? odoo: database: openpg@localhost:5432 
2020-08-04 07:38:13,289 672 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2020-08-04 07:38:15,101 672 INFO ? odoo.service.server: Initiating shutdown 
2020-08-04 07:38:15,102 672 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2020-08-04 07:38:19,303 7912 INFO ? odoo: Odoo version 13.0-20200803 
2020-08-04 07:38:19,303 7912 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 13.0\server\odoo.conf 
2020-08-04 07:38:19,304 7912 INFO ? odoo: addons paths: ['C:\\Program Files (x86)\\Odoo 13.0\\server\\odoo\\addons', 'c:\\users\\administrator\\appdata\\local\\openerp s.a\\odoo\\addons\\13.0', 'c:\\program files (x86)\\odoo 13.0\\server\\odoo\\addons'] 
2020-08-04 07:38:19,304 7912 INFO ? odoo: database: openpg@localhost:5432 
2020-08-04 07:38:19,787 7912 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2020-08-04 07:38:20,108 7912 INFO ? odoo.service.server: HTTP service (werkzeug) running on DESKTOP-JTM8IV4:8069 
2020-08-04 07:38:47,982 7912 INFO ? odoo.http: HTTP Configuring static files 
2020-08-04 07:38:48,054 7912 INFO ? odoo.sql_db: Connection to the database failed 
2020-08-04 07:38:48,057 7912 INFO ? werkzeug: 127.0.0.1 - - [04/Aug/2020 07:38:48] "GET / HTTP/1.1" 500 - 0 0.000 0.040
2020-08-04 07:38:48,079 7912 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\server.py", line 439, in app
    return self.app(e, s)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\middleware\shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1421, in dispatch
    self.setup_db(httprequest)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1344, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1506, in db_monodb
    dbs = db_list(True, httprequest)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1473, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\db.py", line 378, in list_dbs
    with closing(db.cursor()) as cr:
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 654, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 191, in __init__
    self._cnx = pool.borrow(dsn)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 537, in _locked
    return fun(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 605, in borrow
    **connection_info)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "openpg" - - -
2020-08-04 07:38:48,544 7912 INFO ? odoo.sql_db: Connection to the database failed 
2020-08-04 07:38:48,549 7912 INFO ? werkzeug: 127.0.0.1 - - [04/Aug/2020 07:38:48] "GET /favicon.ico HTTP/1.1" 500 - 0 0.000 0.035
2020-08-04 07:38:48,559 7912 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\server.py", line 439, in app
    return self.app(e, s)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\middleware\shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1421, in dispatch
    self.setup_db(httprequest)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1344, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1506, in db_monodb
    dbs = db_list(True, httprequest)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1473, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\db.py", line 378, in list_dbs
    with closing(db.cursor()) as cr:
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 654, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 191, in __init__
    self._cnx = pool.borrow(dsn)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 537, in _locked
    return fun(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 605, in borrow
    **connection_info)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "openpg" - - -
2020-08-04 08:04:39,867 7912 INFO ? odoo.service.server: Initiating shutdown 
2020-08-04 08:04:39,898 7912 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2020-08-04 08:05:31,440 4648 INFO ? odoo: Odoo version 13.0-20200803 
2020-08-04 08:05:31,441 4648 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 13.0\server\odoo.conf 
2020-08-04 08:05:31,441 4648 INFO ? odoo: addons paths: ['C:\\Program Files (x86)\\Odoo 13.0\\server\\odoo\\addons', 'c:\\users\\administrator\\appdata\\local\\openerp s.a\\odoo\\addons\\13.0', 'c:\\program files (x86)\\odoo 13.0\\server\\odoo\\addons'] 
2020-08-04 08:05:31,442 4648 INFO ? odoo: database: openpg@localhost:5432 
2020-08-04 08:05:32,621 4648 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2020-08-04 08:05:33,325 4648 INFO ? odoo.service.server: HTTP service (werkzeug) running on DESKTOP-JTM8IV4:8069 
2020-08-04 09:15:30,370 4648 INFO ? odoo.service.server: Initiating shutdown 
2020-08-04 09:15:30,432 4648 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2020-08-04 16:37:45,468 4188 INFO ? odoo: Odoo version 13.0-20200803 
2020-08-04 16:37:45,469 4188 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 13.0\server\odoo.conf 
2020-08-04 16:37:45,469 4188 INFO ? odoo: addons paths: ['C:\\Program Files (x86)\\Odoo 13.0\\server\\odoo\\addons', 'c:\\users\\administrator\\appdata\\local\\openerp s.a\\odoo\\addons\\13.0', 'c:\\program files (x86)\\odoo 13.0\\server\\odoo\\addons'] 
2020-08-04 16:37:45,469 4188 INFO ? odoo: database: openpg@localhost:5432 
2020-08-04 16:37:46,858 4188 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2020-08-04 16:37:47,724 4188 INFO ? odoo.service.server: HTTP service (werkzeug) running on DESKTOP-JTM8IV4:8069 
2020-08-05 16:20:18,225 4188 INFO ? odoo.service.server: Initiating shutdown 
2020-08-05 16:20:18,272 4188 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2020-08-05 16:21:09,815 4432 INFO ? odoo: Odoo version 13.0-20200803 
2020-08-05 16:21:09,816 4432 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 13.0\server\odoo.conf 
2020-08-05 16:21:09,817 4432 INFO ? odoo: addons paths: ['C:\\Program Files (x86)\\Odoo 13.0\\server\\odoo\\addons', 'c:\\users\\administrator\\appdata\\local\\openerp s.a\\odoo\\addons\\13.0', 'c:\\program files (x86)\\odoo 13.0\\server\\odoo\\addons'] 
2020-08-05 16:21:09,817 4432 INFO ? odoo: database: openpg@localhost:5432 
2020-08-05 16:21:11,277 4432 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2020-08-05 16:21:12,174 4432 INFO ? odoo.service.server: HTTP service (werkzeug) running on DESKTOP-JTM8IV4:8069 
2020-08-05 18:08:12,278 4432 INFO ? odoo.http: HTTP Configuring static files 
2020-08-05 18:08:12,434 4432 INFO chichi_db odoo.sql_db: Connection to the database failed 
2020-08-05 18:08:12,435 4432 INFO chichi_db odoo.http: Generating nondb routing 
2020-08-05 18:08:12,549 4432 INFO chichi_db werkzeug: 127.0.0.1 - - [05/Aug/2020 18:08:12] "GET / HTTP/1.1" 303 - 0 0.000 0.196
2020-08-05 18:08:12,906 4432 INFO ? odoo.sql_db: Connection to the database failed 
2020-08-05 18:08:12,920 4432 INFO ? werkzeug: 127.0.0.1 - - [05/Aug/2020 18:08:12] "GET /web HTTP/1.1" 500 - 0 0.000 0.061
2020-08-05 18:08:13,094 4432 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\server.py", line 439, in app
    return self.app(e, s)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\middleware\shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1421, in dispatch
    self.setup_db(httprequest)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1344, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1506, in db_monodb
    dbs = db_list(True, httprequest)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1473, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\db.py", line 378, in list_dbs
    with closing(db.cursor()) as cr:
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 654, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 191, in __init__
    self._cnx = pool.borrow(dsn)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 537, in _locked
    return fun(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 605, in borrow
    **connection_info)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "openpg" - - -
2020-08-05 18:08:13,150 4432 INFO ? odoo.sql_db: Connection to the database failed 
2020-08-05 18:08:13,156 4432 INFO ? werkzeug: 127.0.0.1 - - [05/Aug/2020 18:08:13] "GET /favicon.ico HTTP/1.1" 500 - 0 0.000 0.046
2020-08-05 18:08:13,165 4432 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\server.py", line 439, in app
    return self.app(e, s)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\middleware\shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1421, in dispatch
    self.setup_db(httprequest)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1344, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1506, in db_monodb
    dbs = db_list(True, httprequest)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1473, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\db.py", line 378, in list_dbs
    with closing(db.cursor()) as cr:
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 654, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 191, in __init__
    self._cnx = pool.borrow(dsn)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 537, in _locked
    return fun(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 605, in borrow
    **connection_info)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "openpg" - - -
2020-08-06 08:53:30,978 4432 INFO ? odoo.service.server: Initiating shutdown 
2020-08-06 08:53:30,995 4432 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2020-08-10 16:41:08,499 4456 INFO ? odoo: Odoo version 13.0-20200803 
2020-08-10 16:41:08,500 4456 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 13.0\server\odoo.conf 
2020-08-10 16:41:08,501 4456 INFO ? odoo: addons paths: ['C:\\Program Files (x86)\\Odoo 13.0\\server\\odoo\\addons', 'c:\\users\\administrator\\appdata\\local\\openerp s.a\\odoo\\addons\\13.0', 'c:\\program files (x86)\\odoo 13.0\\server\\odoo\\addons'] 
2020-08-10 16:41:08,501 4456 INFO ? odoo: database: openpg@localhost:5432 
2020-08-10 16:41:09,993 4456 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2020-08-10 16:41:10,893 4456 INFO ? odoo.service.server: HTTP service (werkzeug) running on DESKTOP-JTM8IV4:8069 
2020-08-13 16:06:35,040 4456 INFO ? odoo.service.server: Initiating shutdown 
2020-08-13 16:06:35,084 4456 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2020-08-13 16:06:51,572 149240 INFO ? odoo: Odoo version 13.0-20200803 
2020-08-13 16:06:51,572 149240 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 13.0\server\odoo.conf 
2020-08-13 16:06:51,573 149240 INFO ? odoo: addons paths: ['C:\\Program Files (x86)\\Odoo 13.0\\server\\odoo\\addons', 'c:\\users\\administrator\\appdata\\local\\openerp s.a\\odoo\\addons\\13.0', 'c:\\program files (x86)\\odoo 13.0\\server\\odoo\\addons'] 
2020-08-13 16:06:51,573 149240 INFO ? odoo: database: openpg@localhost:5432 
2020-08-13 16:06:53,416 149240 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2020-08-13 16:06:54,189 149240 INFO ? odoo.service.server: HTTP service (werkzeug) running on DESKTOP-JTM8IV4:8069 
2020-08-14 01:53:38,400 149240 INFO ? odoo.http: HTTP Configuring static files 
2020-08-14 01:53:38,510 149240 INFO chichi_database odoo.sql_db: Connection to the database failed 
2020-08-14 01:53:38,527 149240 INFO chichi_database werkzeug: 127.0.0.1 - - [14/Aug/2020 01:53:38] "GET /web?debug=assets HTTP/1.1" 500 - 0 0.000 0.095
2020-08-14 01:53:38,771 149240 ERROR chichi_database werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'chichi_database'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\server.py", line 439, in app
    return self.app(e, s)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\werkzeug\middleware\shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 1439, in dispatch
    odoo.registry(db).check_signaling()
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\__init__.py", line 104, in registry
    return modules.registry.Registry(database_name)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\registry.py", line 62, in __new__
    return cls.new(db_name)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\registry.py", line 74, in new
    registry.init(db_name)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\registry.py", line 143, in init
    with closing(self.cursor()) as cr:
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\registry.py", line 523, in cursor
    return self._db.cursor()
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 654, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 191, in __init__
    self._cnx = pool.borrow(dsn)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 537, in _locked
    return fun(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 605, in borrow
    **connection_info)
  File "C:\Program Files (x86)\Odoo 13.0\python\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "openpg" - - -
2020-08-14 01:53:39,447 149240 INFO chichi_database odoo.sql_db: Connection to the database failed 
2020-08-14 01:53:39,448 149240 INFO chichi_database odoo.http: Generating nondb routing 
2020-08-14 01:53:39,508 149240 INFO chichi_database werkzeug: 127.0.0.1 - - [14/Aug/2020 01:53:39] "GET /favicon.ico HTTP/1.1" 404 - 0 0.000 0.101
2020-08-14 09:32:49,955 149240 INFO ? odoo.service.server: Initiating shutdown 
2020-08-14 09:32:49,971 149240 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2020-08-14 09:33:48,926 5404 INFO ? odoo: Odoo version 13.0-20200803 
2020-08-14 09:33:48,928 5404 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 13.0\server\odoo.conf 
2020-08-14 09:33:48,928 5404 INFO ? odoo: addons paths: ['C:\\Program Files (x86)\\Odoo 13.0\\server\\odoo\\addons', 'c:\\users\\administrator\\appdata\\local\\openerp s.a\\odoo\\addons\\13.0', 'c:\\program files (x86)\\odoo 13.0\\server\\odoo\\addons'] 
2020-08-14 09:33:48,928 5404 INFO ? odoo: database: openpg@localhost:5432 
2020-08-14 09:33:50,652 5404 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2020-08-14 09:33:51,146 5404 INFO ? odoo.service.server: HTTP service (werkzeug) running on DESKTOP-JTM8IV4:8069 
2020-08-18 09:37:41,216 5404 INFO ? odoo.service.server: Initiating shutdown 
2020-08-18 09:37:41,265 5404 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2020-08-18 09:37:54,811 126416 INFO ? odoo: Odoo version 13.0-20200803 
2020-08-18 09:37:54,812 126416 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 13.0\server\odoo.conf 
2020-08-18 09:37:54,812 126416 INFO ? odoo: addons paths: ['C:\\Program Files (x86)\\Odoo 13.0\\server\\odoo\\addons', 'c:\\users\\administrator\\appdata\\local\\openerp s.a\\odoo\\addons\\13.0', 'c:\\program files (x86)\\odoo 13.0\\server\\odoo\\addons'] 
2020-08-18 09:37:54,812 126416 INFO ? odoo: database: openpg@localhost:5432 
2020-08-18 09:37:56,206 126416 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2020-08-18 09:37:56,577 126416 INFO ? odoo.service.server: HTTP service (werkzeug) running on DESKTOP-JTM8IV4:8069 
2020-08-19 15:21:21,440 126416 INFO ? odoo.service.server: Initiating shutdown 
2020-08-19 15:21:21,469 126416 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2020-08-19 15:22:52,878 5344 INFO ? odoo: Odoo version 13.0-20200803 
2020-08-19 15:22:52,878 5344 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 13.0\server\odoo.conf 
2020-08-19 15:22:52,878 5344 INFO ? odoo: addons paths: ['C:\\Program Files (x86)\\Odoo 13.0\\server\\odoo\\addons', 'c:\\users\\administrator\\appdata\\local\\openerp s.a\\odoo\\addons\\13.0', 'c:\\program files (x86)\\odoo 13.0\\server\\odoo\\addons'] 
2020-08-19 15:22:52,878 5344 INFO ? odoo: database: openpg@localhost:5432 
2020-08-19 15:22:55,222 5344 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2020-08-19 15:22:55,972 5344 INFO ? odoo.service.server: HTTP service (werkzeug) running on DESKTOP-JTM8IV4:8069 
2020-08-19 15:30:01,563 5344 INFO ? odoo.service.server: Initiating shutdown 
2020-08-19 15:30:01,594 5344 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2020-08-19 15:30:51,545 4196 INFO ? odoo: Odoo version 13.0-20200803 
2020-08-19 15:30:51,546 4196 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 13.0\server\odoo.conf 
2020-08-19 15:30:51,547 4196 INFO ? odoo: addons paths: ['C:\\Program Files (x86)\\Odoo 13.0\\server\\odoo\\addons', 'c:\\users\\administrator\\appdata\\local\\openerp s.a\\odoo\\addons\\13.0', 'c:\\program files (x86)\\odoo 13.0\\server\\odoo\\addons'] 
2020-08-19 15:30:51,547 4196 INFO ? odoo: database: openpg@localhost:5432 
2020-08-19 15:30:52,847 4196 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2020-08-19 15:30:53,982 4196 INFO ? odoo.service.server: HTTP service (werkzeug) running on DESKTOP-JTM8IV4:8069 
